// ====================================================================
// Single source of truth for all website template data.
// Used by: Project.tsx (homepage carousel), mau-website/page.tsx (listing),
//          mau-website/[slug]/page.tsx (detail page)
// ====================================================================

export interface WebsiteTemplate {
    slug: string
    title: string
    category: string          // For homepage filter (translation key)
    categoryId: string        // For listing page filter
    categoryLabel: string     // Display label (Vietnamese)
    subcategories: string[]
    price: string
    time: string
    description: string
    demoUrl: string
    image: string             // Primary thumbnail (carousel + listing)
    mainImages: string[]      // Gallery images (detail page)
    features: string[]
    details: { label: string; value: string }[]
    tags: string[]
    rating: number
    likes: number
}

// All website templates
export const websiteTemplates: WebsiteTemplate[] = [
    {
        slug: 'mau-website-ban-hang-cong-nghe-radios-home-2',
        title: 'Mẫu Website Bán Hàng Công Nghệ - Radios Home 2',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện chuyên nghiệp, thiết kế hiện đại, responsive trên mọi thiết bị và tối ưu chuẩn SEO.',
        demoUrl: 'https://themexriver.com/wp/radios/home-two/',
        image: 'https://123website.com.vn/wp-content/uploads/2023/08/mau-website-ban-hang-cong-nghe-radios-home-2.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/08/mau-website-ban-hang-cong-nghe-radios-home-2.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Responsive', 'SEO', 'Thiết kế đẹp'],
        rating: 4.8,
        likes: 126,
    },
    {
        slug: 'mau-website-noi-that-hama',
        title: 'Mẫu Website Nội Thất - Hama',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website nội thất Hama với giao diện hiện đại, bắt mắt. Thiết kế responsive trên mọi thiết bị và tối ưu chuẩn SEO.',
        demoUrl: 'https://hama.7uptheme.net/',
        image: 'https://123website.com.vn/wp-content/uploads/2018/08/screenshot-7uptheme.com-2018.08.02-08-49-30-603x1024.png',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2018/08/screenshot-7uptheme.com-2018.08.02-08-49-30.png'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Responsive', 'SEO'],
        rating: 4.8,
        likes: 134,
    },
    {
        slug: 'mau-website-noi-that-sns-market',
        title: 'Mẫu Website Nội Thất - Sns Market',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website nội thất Sns Market chuyên nghiệp, thiết kế hiện đại, responsive trên mọi thiết bị và tối ưu chuẩn SEO.',
        demoUrl: 'https://demo.snstheme.com/wp/smarket/',
        image: 'https://123website.com.vn/wp-content/uploads/2018/08/screenshot-demo.snstheme.com-2018.08.02-08-35-46-657x1024.png',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2018/08/screenshot-demo.snstheme.com-2018.08.02-08-35-46.png'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Responsive', 'SEO'],
        rating: 4.8,
        likes: 118,
    },
    {
        slug: 'mau-website-ban-hang-noi-that-big-bazaar-home-4',
        title: 'Mẫu Website Bán Hàng Nội Thất - Big Bazaar Home 4',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website bán hàng nội thất Big Bazaar Home 4 với giao diện hiện đại, tối ưu chuyển đổi và chuẩn SEO.',
        demoUrl: 'https://demo.presslayouts.com/bigbazaar/demo5/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/09/6-3-410x1024.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/09/6-3.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Bán hàng', 'Responsive'],
        rating: 4.8,
        likes: 142,
    },
    {
        slug: 'mau-website-dich-vu-noi-that-cozy',
        title: 'Mẫu Website Dịch Vụ Nội Thất - Cozy',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website dịch vụ nội thất Cozy với thiết kế ấm cúng, sang trọng. Responsive và tối ưu SEO.',
        demoUrl: 'https://cozy.qodeinteractive.com/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/Cozy-Interio-281x1024.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/Cozy-Interio.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Dịch vụ', 'Thiết kế đẹp'],
        rating: 4.9,
        likes: 156,
    },
    {
        slug: 'mau-website-dich-vu-noi-that-ollis-5',
        title: 'Mẫu Website Dịch Vụ Nội Thất - Ollis 5',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website dịch vụ nội thất Ollis 5, thiết kế tối giản, hiện đại. Tối ưu trải nghiệm người dùng và SEO.',
        demoUrl: 'https://ollis.like-themes.com/homepage-mattress/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/Homepage-Mattress-–-Ollis-215x1024.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/Homepage-Mattress-–-Ollis.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Tối giản', 'Modern'],
        rating: 4.7,
        likes: 109,
    },
    {
        slug: 'mau-website-ban-hang-ke-noi-that-ollis-4',
        title: 'Mẫu Website Bán Hàng Nội Thất - Ollis 3',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website bán hàng kệ nội thất Ollis 3 với giao diện chuyên nghiệp, responsive trên mọi thiết bị.',
        demoUrl: 'https://ollis.like-themes.com/homepage-furtniture/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/Homepage-Furtniture-–-Ollis-211x1024.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/Homepage-Furtniture-–-Ollis.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nội thất', 'Bán hàng', 'SEO'],
        rating: 4.8,
        likes: 121,
    },
    {
        slug: 'mau-website-thiet-ke-noi-that-home-decor-blocksy',
        title: 'Mẫu Website Thiết Kế Nội Thất – Home Decor Blocksy',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện hoàn hảo cho công ty thiết kế nội thất, phong cách tối giản, hiện đại.',
        demoUrl: 'https://startersites.io/blocksy/home-decor/',
        image: 'https://123website.com.vn/wp-content/uploads/2023/03/mau-website-thiet-ke-noi-that-home-decor-blocksy-1.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/03/mau-website-thiet-ke-noi-that-home-decor-blocksy-1.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng, Quản trị dễ dàng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Thiết kế', 'Nội thất', 'Mẫu Blocksy'],
        rating: 4.8,
        likes: 120,
    },
    {
        slug: 'mau-website-noi-that-kuteshop',
        title: 'Mẫu Website Nội Thất – Kuteshop',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Kute Shop là mẫu website nội thất dễ thương, thân thiện, với giao diện cửa hàng cực cuốn hút.',
        demoUrl: 'https://html.kutethemes.com/kuteshop/html-rtl/home14.html',
        image: 'https://123website.com.vn/wp-content/uploads/2016/04/screenshot-kutethemes.net-2016-04-11-11-38-16.png',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2016/04/screenshot-kutethemes.net-2016-04-11-11-38-16.png'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'WooCommerce tích hợp' },
            { label: 'SEO', value: 'Tối ưu tốc độ tải trang' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Kuteshop', 'Bán hàng', 'Nội thất'],
        rating: 4.9,
        likes: 185,
    },
    {
        slug: 'mau-website-ban-hang-noi-that-basel',
        title: 'Mẫu Website Bán Hàng Nội Thất Basel',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Thiết kế Basel cổ điển nhưng mang hơi hướng đương đại, phù hợp đa dạng sản phẩm nội thất.',
        demoUrl: 'https://demo.xtemos.com/basel/furniture/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-noi-that-basel.jpeg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-noi-that-basel.jpeg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Basel Framework' },
            { label: 'Tính năng', value: 'Mega Menu' },
            { label: 'SEO', value: 'Tối ưu hình ảnh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Basel', 'Nội thất', 'E-commerce'],
        rating: 4.7,
        likes: 140,
    },
    {
        slug: 'mau-website-ban-hang-phu-kien-trang-tri-seese-home-1',
        title: 'Mẫu Website Bán Hàng Phụ Kiện Trang Trí Seese Home 1',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Tập trung hiển thị trang trí và phụ kiện với phong cách Seese sáng sủa.',
        demoUrl: 'https://victorthemes.com/themes/seese/home/home-masonry/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-seese-home-1.jpeg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-seese-home-1.jpeg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Sáng, Hiện đại' },
            { label: 'Tính năng', value: 'Tích hợp lọc sản phẩm' },
            { label: 'SEO', value: 'Tối ưu On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Trang trí', 'Phụ kiện', 'Seese'],
        rating: 4.6,
        likes: 110,
    },
    {
        slug: 'mau-website-ban-hang-phu-kien-trang-tri-seese',
        title: 'Mẫu Website Bán Hàng Phụ Kiện Trang Trí Seese',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Phiên bản bổ sung của dòng Seese với cấu trúc grid thông minh cho phụ kiện trang trí.',
        demoUrl: 'https://victorthemes.com/themes/seese/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-seese.jpeg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-seese.jpeg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Đầy đủ tính năng' },
            { label: 'SEO', value: 'Cấu trúc web chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Phụ kiện', 'Trang trí', 'Decor'],
        rating: 4.8,
        likes: 198,
    },
    {
        slug: 'mau-website-ban-hang-phu-kien-trang-tri-noi-that-vura',
        title: 'Mẫu Website Bán Hàng Phụ Kiện Trang Trí Nội Thất Vura',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Vura mang tới cho bạn phong cách boutique, rất phù hợp bán sản phẩm phong cách cá nhân.',
        demoUrl: 'https://shtheme.com/demosd/vura/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-noi-that-vura.jpeg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-noi-that-vura.jpeg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Boutique Store' },
            { label: 'Tính năng', value: 'Thanh toán dễ dàng' },
            { label: 'SEO', value: 'Tốc độ cực nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Boutique', 'Vura', 'Trang trí'],
        rating: 4.9,
        likes: 215,
    },
    {
        slug: 'mau-website-ban-hang-phu-kien-trang-tri-noi-that-retbo',
        title: 'Mẫu Website Bán Hàng Phụ Kiện Trang Trí Nội Thất Retbo',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Retbo là một trong những mẫu website phụ kiện nội thất đẹp nhất với tông pastel tinh tế.',
        demoUrl: 'https://codeskdhaka.com/wp/retbo/home-3/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-noi-that-retbo.jpeg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2021/07/mau-website-ban-hang-phu-kien-trang-tri-noi-that-retbo.jpeg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Giao diện pastel' },
            { label: 'Tính năng', value: 'Phân loại danh mục tốt' },
            { label: 'SEO', value: 'Giao diện thân thiện SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Retbo', 'Trang trí', 'Nội thất'],
        rating: 4.8,
        likes: 147,
    },
    {
        slug: 'mau-website-ban-hang-noi-that-gravity',
        title: 'Mẫu Website Bán Hàng Nội Thất – Gravity',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website Gravity đem lại ấn tượng mạnh mẽ cho cửa hàng nội thất cao cấp.',
        demoUrl: 'https://gravity.axiomthemes.com/',
        image: 'https://123website.com.vn/wp-content/uploads/2017/07/mau-website-ban-hang-noi-that-gravity.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2017/07/mau-website-ban-hang-noi-that-gravity.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Sang trọng, Đẳng cấp' },
            { label: 'Tính năng', value: 'Tích hợp giỏ hàng Ajax' },
            { label: 'SEO', value: 'Bộ dữ liệu cấu trúc' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Gravity', 'Cao cấp', 'Nội thất'],
        rating: 4.9,
        likes: 310,
    },
    {
        slug: 'mau-website-ban-hang-plumbing',
        title: 'Mẫu Website Bán Hàng – Plumbing',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Dành riêng cho thiết bị vệ sinh cao cấp và phụ kiện nội thất liên quan. Phong cách cứng cáp vững chãi.',
        demoUrl: 'https://plumbing-parts.themerex.net/',
        image: 'https://123website.com.vn/wp-content/uploads/2016/07/screenshot-plumbing-parts.themerex.net-2016-07-12-14-15-32.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2016/07/screenshot-plumbing-parts.themerex.net-2016-07-12-14-15-32.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Công nghiệp, Cứng cáp' },
            { label: 'Tính năng', value: 'Catalogue sản phẩm' },
            { label: 'SEO', value: 'Chuẩn SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Thiết bị vệ sinh', 'Plumbing', 'Phụ kiện'],
        rating: 4.5,
        likes: 120,
    },
    {
        slug: 'mau-website-ban-hang-noi-that-home-fabric-modus',
        title: 'Mẫu Website Bán Hàng Nội Thất – Home Fabric – Modus',
        category: 'interior',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website bán hàng nội thất'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Tập trung chủ yếu vào vải vóc, rèm cửa, sofa nỉ trang trí cho một mái ấm hoàn thiện.',
        demoUrl: 'http://demo.arrowpress.net/modus/furniture-8/',
        image: 'https://123website.com.vn/wp-content/uploads/2019/04/screenshot-demo.arrowpress.net-2019.04.23-11-00-07.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2019/04/screenshot-demo.arrowpress.net-2019.04.23-11-00-07.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Cảm giác mềm mại, ấm cúng' },
            { label: 'Tính năng', value: 'So sánh sản phẩm' },
            { label: 'SEO', value: 'Sitemap tự động' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Sofa', 'Fabric', 'Modus'],
        rating: 4.8,
        likes: 215,
    },
    {
        slug: 'mau-website-dich-vu-ca-phe-barista-modern',
        title: 'Mẫu Website Cafe – Barista Modern',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện hoàn hảo cho quán cafe, nhà hàng với thiết kế hiện đại, tinh tế.',
        demoUrl: 'https://barista.qodeinteractive.com/elementor/metro-home/',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-ca-phe-5.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-ca-phe-5.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Quản trị dễ dàng, Menu rõ ràng' },
            { label: 'SEO', value: 'Tối ưu SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Cafe', 'Dịch vụ', 'Barista'],
        rating: 4.8,
        likes: 154,
    },
    {
        slug: 'mau-website-dich-vu-du-lich-adventis',
        title: 'Mẫu Website Dịch Vụ Du Lịch – Adventis',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website du lịch'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website dịch vụ du lịch Adventis chuyên nghiệp, với tính năng đặt tour chuẩn xác.',
        demoUrl: 'https://demo2.themelexus.com/adventis/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/09/dang-website-1.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2024/09/dang-website-1.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Responsive, Mobile First' },
            { label: 'Tính năng', value: 'Booking tour' },
            { label: 'SEO', value: 'Tối ưu chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Du lịch', 'Tour', 'Adventis'],
        rating: 4.9,
        likes: 210,
    },
    {
        slug: 'mau-website-dich-vu-du-lich-sealosca',
        title: 'Mẫu Website Dịch Vụ Du Lịch – Sealosca',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website du lịch'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Sealosca mang phong cách hiện đại biển khơi, phù hợp cho resort, khu nghỉ dưỡng, tour du lịch.',
        demoUrl: 'https://templatekit.kotakkuning.com/sealosca/template-kit/home/',
        image: 'https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Sáng tạo, Hiện đại' },
            { label: 'Tính năng', value: 'Phân loại tour dễ dàng' },
            { label: 'SEO', value: 'Tối ưu On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Du lịch', 'Khu nghỉ dưỡng', 'Sealosca'],
        rating: 4.7,
        likes: 182,
    },
    {
        slug: 'mau-website-dich-vu-dinh-cu-visa-travisa',
        title: 'Mẫu Website Dịch Vụ Định Cư Visa – Travisa',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website thông tin'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website tư vấn định cư, làm visa chuyên nghiệp mang tên Travisa.',
        demoUrl: 'https://templatekit.jegtheme.com/travisa/?storefront=envato-elements',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-dich-vu-dinh-cu-visa-3.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-dich-vu-dinh-cu-visa-3.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Bố cục rõ ràng, chuyên nghiệp' },
            { label: 'Tính năng', value: 'Form tư vấn' },
            { label: 'SEO', value: 'Cấu trúc web chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Visa', 'Định cư', 'Tư vấn'],
        rating: 4.8,
        likes: 165,
    },
    {
        slug: 'mau-website-dich-vu-khach-san-the-resort',
        title: 'Mẫu Website Dịch Vụ Khách Sạn – The Resort',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website khách sạn'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'The Resort mang đến trải nghiệm đặt phòng khách sạn, homestay với giao diện cực kỳ sang trọng.',
        demoUrl: 'https://www.nicdarkthemes.com/themes/hotel-booking/wp/demo/resort/',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-khach-san.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-khach-san.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Cao cấp, tinh tế' },
            { label: 'Tính năng', value: 'Booking phòng khách sạn' },
            { label: 'SEO', value: 'Tốc độ cực nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Khách sạn', 'Resort', 'Homestay'],
        rating: 4.9,
        likes: 245,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-gofoodie',
        title: 'Mẫu Website Dịch Vụ Nhà Hàng – Gofoodie',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Gofoodie là mẫu trang web ẩm thực, nhà hàng với hệ thống đặt bàn và hiển thị thực đơn vô cùng hấp dẫn.',
        demoUrl: 'https://templatekits.wpmarvels.com/gofoodie/?storefront=envato-elements',
        image: 'https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-4.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-4.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Hình ảnh sống động' },
            { label: 'Tính năng', value: 'Booking bàn, hiển thị menu' },
            { label: 'SEO', value: 'Thân thiện di động' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Nhà hàng', 'Ẩm thực', 'Đặt bàn'],
        rating: 4.8,
        likes: 198,
    },
    {
        slug: 'mau-website-khoa-hoc-online-educrat',
        title: 'Mẫu Website Khoá Học Online – Educrat',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Educrat hỗ trợ hiển thị khoá học online bài bản, giúp cơ sở giáo dục vận hành E-learning hiệu quả.',
        demoUrl: 'https://demoapus1.com/educrat/learnpress/home-2/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-4.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-4.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Thông tin học tập rõ ràng' },
            { label: 'Tính năng', value: 'Đăng ký khoá học online' },
            { label: 'SEO', value: 'Chuẩn dữ liệu' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Khoá học', 'Đào tạo', 'Educrat'],
        rating: 4.9,
        likes: 310,
    },
    {
        slug: 'mau-website-khoa-hoc-online-eduvison',
        title: 'Mẫu Website Khoá Học Online – Eduvison',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện hoàn hảo dành cho trường học, trung tâm ngoại ngữ, và dạy kỹ năng.',
        demoUrl: 'https://shtheme.com/demosd/eduvisionwp/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Màu sắc trường học thân thiện' },
            { label: 'Tính năng', value: 'Quản lý khóa học, học viên' },
            { label: 'SEO', value: 'Load cực nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Trường học', 'Trung tâm', 'Học viên'],
        rating: 4.7,
        likes: 125,
    },
    {
        slug: 'mau-website-khoa-hoc-online-skola',
        title: 'Mẫu Website Khoá Học Online – Skola',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Skola ưu tiên tập trung vào việc bán các khóa đào tạo trực tuyến qua các video bài giảng.',
        demoUrl: 'https://skola.madrasthemes.com/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-2.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-2.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Tập trung hiển thị nội dung' },
            { label: 'Tính năng', value: 'Giỏ hàng khóa học' },
            { label: 'SEO', value: 'Tối ưu thân thiện Google' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Học trực tuyến', 'Đào tạo', 'Skola'],
        rating: 4.8,
        likes: 180,
    },
    {
        slug: 'mau-website-khoa-hoc-online-zoomy',
        title: 'Mẫu Website Khoá Học Online – Zoomy',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu thiết kế đa năng dành cho trung tâm gia sư, lớp học ngắn hạn hoặc học từ xa.',
        demoUrl: 'https://wordpress-theme.spider-themes.net/zoomy/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-3.jpg',
        mainImages: [
            'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-3.jpg'
        ],
        features: [
            'Tặng tên miền quốc tế .com',
            'Tặng Hosting 4 GB',
            'Thiết kế chuẩn UX/UI',
            'Tối ưu chuẩn SEO',
            'Bảo hành trọn đời'
        ],
        details: [
            { label: 'Thiết kế', value: 'Hiện đại, chuyên gia' },
            { label: 'Tính năng', value: 'Tích hợp thanh toán' },
            { label: 'SEO', value: 'On-page SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Gia sư', 'Đào tạo', 'Zoomy'],
        rating: 4.9,
        likes: 245,
    },
    {
        slug: 'mau-website-olympic-uef',
        title: 'Website Olympic UEF',
        category: 'education',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website thi trắc nghiệm và tin tức thể thao Olympic dành cho các trường đại học, cơ sở giáo dục.',
        demoUrl: 'https://shtheme.com/demosd/eduvisionwp/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Hiện đại, chuyên nghiệp' },
            { label: 'Tính năng', value: 'Thi trắc nghiệm, tin tức' },
            { label: 'SEO', value: 'On-page SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['UEF', 'Đại học', 'Olympic'],
        rating: 4.9,
        likes: 188,
    },
    {
        slug: 'mau-website-my-pham-sonatural',
        title: 'Website Mỹ Phẩm So’Natural',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website mỹ phẩm'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website bán hàng mỹ phẩm So’Natural phong cách Hàn Quốc hiện đại, hình ảnh chân thực, tối ưu chuyển đổi giỏ hàng.',
        demoUrl: 'https://123websitedemo.com/?id=22948',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Giao diện hồng phấn nhẹ nhàng' },
            { label: 'Tính năng', value: 'Đặt mua online, thanh toán' },
            { label: 'SEO', value: 'Thân thiện Google' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Mỹ phẩm', 'Bán hàng', 'SoNatural'],
        rating: 4.8,
        likes: 215,
    },
    {
        slug: 'mau-website-my-pham-lilybyred',
        title: 'Website Mỹ Phẩm Lilybyred',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website mỹ phẩm'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện website giới thiệu và phân phối độc quyền dòng mỹ phẩm Lilybyred với tone màu trẻ trung, bắt mắt.',
        demoUrl: 'https://123websitedemo.com/?id=22948',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Màu sắc trẻ trung năng động' },
            { label: 'Tính năng', value: 'Giỏ hàng, review sản phẩm' },
            { label: 'SEO', value: 'Tốc độ load nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Mỹ phẩm', 'Lilybyred', 'Bán hàng'],
        rating: 4.9,
        likes: 312,
    },
    {
        slug: 'mau-website-giao-duc-blockchain',
        title: 'Website Giáo Dục Blockchain',
        category: 'education',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Website đào tạo, chia sẻ kiến thức về công nghệ Blockchain, tích hợp E-learning và cấp chứng chỉ trực tuyến.',
        demoUrl: 'https://demoapus1.com/educrat/learnpress/home-2/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-4.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-4.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Công nghệ, hiện đại' },
            { label: 'Tính năng', value: 'Video học tập, cấp chứng chỉ' },
            { label: 'SEO', value: 'Cấu trúc bài viết chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Blockchain', 'Đào tạo', 'E-learning'],
        rating: 4.9,
        likes: 275,
    },
    {
        slug: 'mau-website-du-thuyen-vinh-ha-long',
        title: 'Website Du Thuyền Vịnh Hạ Long',
        category: 'intro',
        categoryId: 'thong-tin',
        categoryLabel: 'Mẫu website giới thiệu',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website du lịch'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website du lịch, đặt tour du thuyền Hạ Long hạng sang với giao diện hiển thị hình ảnh rộng lớn, kích thích đặt phòng.',
        demoUrl: 'https://123websitedemo.com/?id=24192',
        image: 'https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Sang trọng, phóng khoáng' },
            { label: 'Tính năng', value: 'Đặt tour, kiểm tra phòng trống' },
            { label: 'SEO', value: 'Tập trung từ khóa du lịch' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Du thuyền', 'Hạ Long', 'Tour du lịch'],
        rating: 4.8,
        likes: 198,
    },
    {
        slug: 'mau-website-tham-my-vien',
        title: 'Website Thẩm Mỹ Viện Quốc Tế',
        category: 'intro',
        categoryId: 'thong-tin',
        categoryLabel: 'Mẫu website giới thiệu',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website làm đẹp'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện sang trọng đẳng cấp dành cho các Spa, thẩm mỹ viện và phòng khám da liễu chuyên nghiệp.',
        demoUrl: 'https://123websitedemo.com/?id=24264',
        image: 'https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-tiec-cuoi-3.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-tiec-cuoi-3.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Luxury, tone vàng gold' },
            { label: 'Tính năng', value: 'Đặt lịch hẹn trực tuyến' },
            { label: 'SEO', value: 'Chuẩn UX/UI y khoa' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Spa', 'Thẩm mỹ viện', 'Làm đẹp'],
        rating: 4.9,
        likes: 240,
    },
    {
        slug: 'mau-website-tieng-anh',
        title: 'Website Trung Tâm Tiếng Anh',
        category: 'education',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website đào tạo'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện năng động dành cho trung tâm tiếng Anh trẻ em, giao tiếp người lớn, đăng ký lịch học thử và test trình độ đầu vào.',
        demoUrl: 'https://skola.madrasthemes.com/',
        image: 'https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-2.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2024/03/mau-website-khoa-hoc-2.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Tươi sáng, năng động' },
            { label: 'Tính năng', value: 'Đăng ký học thử, test đầu vào' },
            { label: 'SEO', value: 'Load cực nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Tiếng Anh', 'Trung tâm', 'Học thử'],
        rating: 4.8,
        likes: 185,
    },
    {
        slug: 'mau-website-trang-suc',
        title: 'Website Bán Trang Sức Luxury',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website trang sức'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website bán trang sức luxury, đá quý cao cấp với thiết kế tỉ mỉ, tôn vinh độ sắc nét của hình ảnh sản phẩm.',
        demoUrl: 'https://hama.7uptheme.net/',
        image: 'https://123website.com.vn/wp-content/uploads/2018/08/screenshot-7uptheme.com-2018.08.02-08-49-30-603x1024.png',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2018/08/screenshot-7uptheme.com-2018.08.02-08-49-30.png'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Tối giản, quý phái' },
            { label: 'Tính năng', value: 'Zoom sản phẩm độ nét cao' },
            { label: 'SEO', value: 'Thân thiện di động' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Trang sức', 'Vàng bạc', 'Luxury'],
        rating: 4.9,
        likes: 298,
    },
    {
        slug: 'mau-website-smarthome',
        title: 'Website Giải Pháp Smarthome',
        category: 'intro',
        categoryId: 'thong-tin',
        categoryLabel: 'Mẫu website giới thiệu',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website công nghệ'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website giới thiệu thiết bị điện thông minh và lắp đặt hệ thống Smarthome trọn gói cho nhà phố, biệt thự.',
        demoUrl: 'https://demo.presslayouts.com/bigbazaar/demo5/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/09/6-3-410x1024.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2021/09/6-3.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Hiện đại, đậm chất tech' },
            { label: 'Tính năng', value: 'Báo giá nhanh thiết bị' },
            { label: 'SEO', value: 'On-page chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Smarthome', 'Nhà thông minh', 'Công nghệ'],
        rating: 4.8,
        likes: 167,
    },
    {
        slug: 'mau-website-yoga-tri-lieu',
        title: 'Website Phòng Tập Yoga Trị Liệu',
        category: 'intro',
        categoryId: 'thong-tin',
        categoryLabel: 'Mẫu website giới thiệu',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website sức khỏe'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện website phòng tập Yoga trị liệu, thiền định với tone màu dịu nhẹ mang lại cảm giác thư thái cho người truy cập.',
        demoUrl: 'https://cozy.qodeinteractive.com/',
        image: 'https://123website.com.vn/wp-content/uploads/2021/07/Cozy-Interio-281x1024.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2021/07/Cozy-Interio.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Tone màu xanh matcha dịu mát' },
            { label: 'Tính năng', value: 'Đăng ký thẻ tập, xem lịch lớp' },
            { label: 'SEO', value: 'Tối ưu hóa hình ảnh' },
            { label: 'Bảo hành', value: 'Trọn đời' },
        ],
        tags: ['Yoga', 'Sức khỏe', 'Thiền định'],
        rating: 4.9,
        likes: 154,
    },
    {
        slug: 'mau-website-ban-hang-my-pham-avesa-home-2',
        title: 'Mẫu Website Bán Hàng Mỹ Phẩm - Avesa Home 2',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website mỹ phẩm'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện bán hàng mỹ phẩm Avesa Home 2 thiết kế dịu nhẹ, sang trọng, tương thích tốt trên di động.',
        demoUrl: 'https://123websitedemo.com/?id=22948',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-my-pham-avesa-home-2.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Sang trọng, tinh tế' },
            { label: 'Tính năng', value: 'Mua hàng nhanh, thanh toán' },
            { label: 'SEO', value: 'Chuẩn SEO Onpage' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Mỹ phẩm', 'Bán hàng', 'Avesa'],
        rating: 4.8,
        likes: 145,
    },
    {
        slug: 'mau-website-ban-hang-san-pham-nong-nghiep-vano',
        title: 'Mẫu Website Bán Hàng Nông Sản - Vano',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website nông nghiệp'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu giao diện bán hàng nông sản, rau củ quả hữu cơ Vano với màu xanh tươi mát, chuyên nghiệp.',
        demoUrl: 'https://123websitedemo.com/?id=23133',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-san-pham-nong-nghiep-1.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/06/mau-website-ban-hang-san-pham-nong-nghiep-1.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Tươi sáng, thiên nhiên' },
            { label: 'Tính năng', value: 'Đặt hàng, cân nặng sản phẩm' },
            { label: 'SEO', value: 'Chuẩn SEO Google' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nông sản', 'Rau củ', 'Bán hàng'],
        rating: 4.7,
        likes: 120,
    },
    {
        slug: 'mau-website-ban-nuoc-hoa-perfume-store-2',
        title: 'Mẫu Website Bán Nước Hoa - Perfume Store 2',
        category: 'selling',
        categoryId: 'ban-hang',
        categoryLabel: 'Mẫu website bán hàng',
        subcategories: ['Mẫu website bán hàng', 'Mẫu website nước hoa'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện website bán nước hoa, mỹ phẩm cao cấp với thiết kế huyền bí, sang trọng và thu hút.',
        demoUrl: 'https://123websitedemo.com/?id=22622',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-ban-nuoc-hoa-4.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/05/mau-website-ban-nuoc-hoa-4.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Luxury, huyền bí' },
            { label: 'Tính năng', value: 'Bộ lọc mùi hương, thương hiệu' },
            { label: 'SEO', value: 'Onpage hoàn hảo' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nước hoa', 'Bán hàng', 'Mỹ phẩm'],
        rating: 4.9,
        likes: 198,
    },
    {
        slug: 'mau-website-dich-vu-du-lich-adventis',
        title: 'Mẫu Website Dịch Vụ Du Lịch - Adventis',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website du lịch'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website công ty lữ hành du lịch Adventis với thiết kế hiện đại, nhiều tính năng đăng ký tour.',
        demoUrl: 'https://123websitedemo.com/?id=24945',
        image: 'https://123website.com.vn/wp-content/uploads/2024/09/dang-website-1.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2024/09/dang-website-1.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Năng động, tươi trẻ' },
            { label: 'Tính năng', value: 'Đặt tour, lịch trình chi tiết' },
            { label: 'SEO', value: 'Cấu trúc tour chuẩn SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Du lịch', 'Đặt tour', 'Adventis'],
        rating: 4.9,
        likes: 210,
    },
    {
        slug: 'mau-website-dich-vu-du-lich-sealosca',
        title: 'Mẫu Website Du Lịch Biển - Sealosca',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website du lịch'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website chuyên về tour biển đảo, đặt phòng resort ven biển cực đẹp mắt và chuyên nghiệp.',
        demoUrl: 'https://123websitedemo.com/?id=24192',
        image: 'https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/10/2mau-website-dich-vu-du-lich.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Xanh dương đại dương' },
            { label: 'Tính năng', value: 'Đặt phòng, hiển thị tour' },
            { label: 'SEO', value: 'Load nhanh, chuẩn Google' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Du lịch', 'Biển đảo', 'Resort'],
        rating: 4.8,
        likes: 189,
    },
    {
        slug: 'mau-website-dich-vu-dinh-cu-visa-travisa',
        title: 'Mẫu Website Dịch Vụ Định Cư - Visa Travisa',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website visa', 'Mẫu website định cư'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện chuyên nghiệp dành cho công ty tư vấn định cư nước ngoài, làm visa du học, du lịch nhanh chóng.',
        demoUrl: 'https://123websitedemo.com/?id=23157',
        image: 'https://123website.com.vn/wp-content/uploads/2023/06/mau-website-dich-vu-dinh-cu-visa-3.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/06/mau-website-dich-vu-dinh-cu-visa-3.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Tin cậy, chuyên nghiệp' },
            { label: 'Tính năng', value: 'Đăng ký tư vấn, dịch vụ trọn gói' },
            { label: 'SEO', value: 'Đầy đủ schema metadata' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Định cư', 'Visa', 'Du học'],
        rating: 4.9,
        likes: 278,
    },
    {
        slug: 'mau-website-dich-vu-khach-san-the-resort',
        title: 'Mẫu Website Khách Sạn - The Resort',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website khách sạn'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện khách sạn, homestay, resort sang trọng tích hợp hệ thống đặt phòng trực quan.',
        demoUrl: 'https://123websitedemo.com/?id=22561',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-khach-san.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-khach-san.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Luxury, tối giản' },
            { label: 'Tính năng', value: 'Booking phòng trực tiếp' },
            { label: 'SEO', value: 'Tối ưu tốc độ load' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Khách sạn', 'Resort', 'Homestay'],
        rating: 4.8,
        likes: 195,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-gofoodie',
        title: 'Mẫu Website Nhà Hàng - Gofoodie',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Website nhà hàng Gofoodie đẹp mắt hiển thị các món ăn ngon miệng và tích hợp đặt bàn trước.',
        demoUrl: 'https://123websitedemo.com/?id=23673',
        image: 'https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-4.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-4.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Hiện đại, trực quan' },
            { label: 'Tính năng', value: 'Đặt bàn trước, hiển thị menu' },
            { label: 'SEO', value: 'Thân thiện di động' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nhà hàng', 'Đặt bàn', 'Ẩm thực'],
        rating: 4.8,
        likes: 167,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-grand-restaurant',
        title: 'Mẫu Website Nhà Hàng - Grand Restaurant',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Thiết kế website nhà hàng tiệc cưới, tổ chức sự kiện Grand Restaurant mang phong cách quý phái, đẳng cấp.',
        demoUrl: 'https://123websitedemo.com/?id=24319',
        image: 'https://123website.com.vn/wp-content/uploads/2024/01/4mau-website-dich-vu-nha-hang.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2024/01/4mau-website-dich-vu-nha-hang.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Cổ điển, sang trọng' },
            { label: 'Tính năng', value: 'Đặt phòng tiệc, liên hệ nhanh' },
            { label: 'SEO', value: 'Chuẩn SEO Onpage' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nhà hàng', 'Tiệc cưới', 'Sự kiện'],
        rating: 4.9,
        likes: 245,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-organic-restaurant',
        title: 'Mẫu Website Nhà Hàng Organic',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website nhà hàng đồ ăn kiêng, organic chay tịnh, đem lại sự thân thiện môi trường và sức khỏe.',
        demoUrl: 'https://123websitedemo.com/?id=22557',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-nha-hang-4.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-nha-hang-4.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Mộc mạc, thiên nhiên' },
            { label: 'Tính năng', value: 'Xem thực đơn, đặt món online' },
            { label: 'SEO', value: 'Google Index nhanh' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nhà hàng', 'Organic', 'Đồ chay'],
        rating: 4.7,
        likes: 132,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-ristera',
        title: 'Mẫu Website Nhà Hàng - Ristera',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Website nhà hàng buffet, lẩu nướng Ristera với giao diện ấn tượng, kích thích vị giác khách hàng.',
        demoUrl: 'https://123websitedemo.com/?id=23677',
        image: 'https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-5-1.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/07/mau-website-dich-vu-nha-hang-5-1.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Trẻ trung, hiện đại' },
            { label: 'Tính năng', value: 'Hiển thị các combo, khuyến mãi' },
            { label: 'SEO', value: 'Tốc độ load cực cao' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Nhà hàng', 'Buffet', 'Lẩu nướng'],
        rating: 4.8,
        likes: 178,
    },
    {
        slug: 'mau-website-dich-vu-nha-hang-sovy-2',
        title: 'Mẫu Website Quán Ăn - Sovy 2',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website nhà hàng'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website quán ăn gia đình, giao diện ấm cúng, thiết kế tinh giản giúp đặt món nhanh gọn.',
        demoUrl: 'https://123websitedemo.com/?id=22553',
        image: 'https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-nha-hang-2.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/05/mau-website-dich-vu-nha-hang-2.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Đơn giản, tinh tế' },
            { label: 'Tính năng', value: 'Đặt giao hàng tận nơi' },
            { label: 'SEO', value: 'Tương thích di động' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Quán ăn', 'Nhà hàng', 'Đặt món'],
        rating: 4.8,
        likes: 145,
    },
    {
        slug: 'mau-website-dich-vu-tiec-cuoi-bridely',
        title: 'Mẫu Website Tiệc Cưới - Bridely',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website tiệc cưới'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website trung tâm tiệc cưới Bridely thiết kế lãng mạn, thanh lịch trưng bày dịch vụ cưới trọn gói.',
        demoUrl: 'https://123websitedemo.com/?id=24264',
        image: 'https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-tiec-cuoi-3.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-tiec-cuoi-3.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Thanh lịch, lãng mạn' },
            { label: 'Tính năng', value: 'Chọn sảnh tiệc, menu tiệc cưới' },
            { label: 'SEO', value: 'Load nhanh, chuẩn' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Tiệc cưới', 'Sự kiện', 'Trung tâm'],
        rating: 4.8,
        likes: 198,
    },
    {
        slug: 'mau-website-dich-vu-tiec-cuoi-wedda',
        title: 'Mẫu Website Tiệc Cưới - Wedda',
        category: 'service',
        categoryId: 'dich-vu',
        categoryLabel: 'Mẫu website dịch vụ',
        subcategories: ['Mẫu website dịch vụ', 'Mẫu website tiệc cưới'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Giao diện album ảnh cưới và tổ chức sự kiện tiệc cưới Wedda với thiết kế hiện đại, tôn vinh hình ảnh cặp đôi.',
        demoUrl: 'https://123websitedemo.com/?id=24256',
        image: 'https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-cuoi.jpg',
        mainImages: ['https://123website.com.vn/wp-content/uploads/2023/12/mau-website-dich-vu-cuoi.jpg'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Thơ mộng, tươi sáng' },
            { label: 'Tính năng', value: 'Xem album ảnh cưới, bản đồ' },
            { label: 'SEO', value: 'Chuẩn SEO Onpage' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Album cưới', 'Tiệc cưới', 'Sự kiện'],
        rating: 4.9,
        likes: 215,
    },
    {
        slug: 'mau-website-cong-ty-bat-dong-san',
        title: 'Mẫu Website Công Ty Bất Động Sản',
        category: 'realEstate',
        categoryId: 'bat-dong-san',
        categoryLabel: 'Mẫu website bất động sản',
        subcategories: ['Mẫu website bất động sản', 'Mẫu website doanh nghiệp'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website giới thiệu công ty bất động sản chuyên nghiệp, giao diện hiện đại và tối ưu chuẩn SEO.',
        demoUrl: 'https://datnamholdings-bds.com.vn/',
        image: 'https://k-tech.net.vn/wp-content/uploads/2026/03/website-cong-ty-bat-dong-san-768x1706.webp',
        mainImages: ['https://k-tech.net.vn/wp-content/uploads/2026/03/website-cong-ty-bat-dong-san.webp'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Hiện đại, uy tín' },
            { label: 'Tính năng', value: 'Giới thiệu dự án, liên hệ' },
            { label: 'SEO', value: 'Chuẩn SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Bất động sản', 'Doanh nghiệp', 'K-Tech'],
        rating: 4.8,
        likes: 152,
    },
    {
        slug: 'mau-website-ca-nhan-moi-gioi-bat-dong-san',
        title: 'Mẫu Website Cá Nhân Môi Giới Bất Động Sản',
        category: 'realEstate',
        categoryId: 'bat-dong-san',
        categoryLabel: 'Mẫu website bất động sản',
        subcategories: ['Mẫu website bất động sản', 'Mẫu website cá nhân'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website cá nhân môi giới bất động sản giúp môi giới xây dựng thương hiệu cá nhân và giới thiệu giỏ hàng chuyên nghiệp.',
        demoUrl: 'https://tinhrealtorhomethuduc.com/',
        image: 'https://k-tech.net.vn/wp-content/uploads/2026/03/website-ca-nhan-moi-gioi-bat-dong-san-768x3713.webp',
        mainImages: ['https://k-tech.net.vn/wp-content/uploads/2026/03/website-ca-nhan-moi-gioi-bat-dong-san.webp'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Trực quan, cá nhân hóa' },
            { label: 'Tính năng', value: 'Quản lý giỏ hàng, liên hệ Zalo' },
            { label: 'SEO', value: 'Chuẩn SEO On-page' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Bất động sản', 'Môi giới', 'Cá nhân'],
        rating: 4.9,
        likes: 184,
    },
    {
        slug: 'mau-website-tap-doan-bat-dong-san-2',
        title: 'Mẫu Website Tập Đoàn Bất Động Sản',
        category: 'realEstate',
        categoryId: 'bat-dong-san',
        categoryLabel: 'Mẫu website bất động sản',
        subcategories: ['Mẫu website bất động sản', 'Mẫu website tập đoàn'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website tập đoàn bất động sản với quy mô lớn, tích hợp hệ sinh thái dự án và thông tin cổ đông chuyên nghiệp.',
        demoUrl: 'https://f5-group.vn/',
        image: 'https://k-tech.net.vn/wp-content/uploads/2026/04/Website-tap-doan-bat-dong-san-768x2265.webp',
        mainImages: ['https://k-tech.net.vn/wp-content/uploads/2026/04/Website-tap-doan-bat-dong-san.webp'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Đẳng cấp, tin cậy' },
            { label: 'Tính năng', value: 'Hệ sinh thái dự án, tin tức tập đoàn' },
            { label: 'SEO', value: 'Tối ưu SEO' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Bất động sản', 'Tập đoàn', 'Quy mô lớn'],
        rating: 4.9,
        likes: 201,
    },
    {
        slug: 'mau-website-du-an-nha-o-chuong-duong-homeland',
        title: 'Mẫu Website Dự Án Nhà Ở Chương Dương Homeland',
        category: 'realEstate',
        categoryId: 'bat-dong-san',
        categoryLabel: 'Mẫu website bất động sản',
        subcategories: ['Mẫu website bất động sản', 'Mẫu website dự án'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website landing page giới thiệu dự án nhà ở, căn hộ chung cư Chương Dương Homeland với thiết kế hiện đại, đầy đủ thông tin mặt bằng.',
        demoUrl: 'https://cdhomelanddanang.vn/',
        image: 'https://k-tech.net.vn/wp-content/uploads/2026/04/Website-du-an-nha-o-Chuong-Duong-homeland-768x5178.webp',
        mainImages: ['https://k-tech.net.vn/wp-content/uploads/2026/04/Website-du-an-nha-o-Chuong-Duong-homeland.webp'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Landing page hiện đại' },
            { label: 'Tính năng', value: 'Bảng giá, mặt bằng, form đăng ký' },
            { label: 'SEO', value: 'Tối ưu tốc độ tải trang' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Bất động sản', 'Dự án', 'Căn hộ'],
        rating: 4.8,
        likes: 176,
    },
    {
        slug: 'mau-website-mua-ban-nha-dat',
        title: 'Mẫu Website Mua Bán Nhà Đất',
        category: 'realEstate',
        categoryId: 'bat-dong-san',
        categoryLabel: 'Mẫu website bất động sản',
        subcategories: ['Mẫu website bất động sản', 'Mẫu website mua bán'],
        price: 'Liên hệ',
        time: '3-5 ngày',
        description: 'Mẫu website cổng thông tin mua bán, ký gửi nhà đất chuyên nghiệp với bộ lọc tìm kiếm thông minh và bản đồ trực quan.',
        demoUrl: 'https://ducsonnhadat.com/',
        image: 'https://k-tech.net.vn/wp-content/uploads/2025/11/website-mua-ban-nha-dat-768x2053.png',
        mainImages: ['https://k-tech.net.vn/wp-content/uploads/2025/11/website-mua-ban-nha-dat-scaled.png'],
        features: ['Tặng tên miền quốc tế .com', 'Tặng Hosting 4 GB', 'Thiết kế chuẩn UX/UI', 'Tối ưu chuẩn SEO', 'Bảo hành trọn đời'],
        details: [
            { label: 'Thiết kế', value: 'Portal tin cậy, rõ ràng' },
            { label: 'Tính năng', value: 'Tìm kiếm nâng cao, ký gửi trực tuyến' },
            { label: 'SEO', value: 'Chuẩn SEO Onpage' },
            { label: 'Bảo hành', value: 'Trọn đời' }
        ],
        tags: ['Bất động sản', 'Mua bán', 'Ký gửi'],
        rating: 4.7,
        likes: 195,
    }
]

// Build database lookup by slug for detail pages
export const websiteDatabase: Record<string, WebsiteTemplate> = Object.fromEntries(
    websiteTemplates.map(t => [t.slug, t])
)

// Default template for any slug not found in database
export const defaultTemplate: Omit<WebsiteTemplate, 'slug'> = {
    title: 'Mẫu Website',
    category: 'selling',
    categoryId: 'ban-hang',
    categoryLabel: 'Mẫu website bán hàng',
    subcategories: ['Báo giá'],
    price: 'Liên hệ',
    time: '3-5 ngày',
    description: 'Mẫu website chuyên nghiệp với thiết kế hiện đại, tối ưu SEO và responsive.',
    demoUrl: 'https://123website.com.vn',
    image: '/projects/website-my-pham-ceranle.png',
    mainImages: [
        '/projects/website-my-pham-ceranle.png',
    ],
    features: [
        'Tặng tên miền quốc tế .com',
        'Tặng Hosting 4 GB',
        'Hỗ trợ kỹ thuật trọn đời',
    ],
    details: [
        { label: 'Thiết kế', value: 'Responsive, Mobile First' },
        { label: 'Tính năng', value: 'Đầy đủ tính năng cơ bản' },
        { label: 'SEO', value: 'Tối ưu SEO On-page' },
        { label: 'Bảo hành', value: 'Trọn đời' },
    ],
    tags: ['Responsive', 'SEO', 'Modern'],
    rating: 4.8,
    likes: 50,
}

// Listing page categories with correct counts
export const listingCategories = [
    { id: 'all', name: 'Tất cả', count: websiteTemplates.length },
    { id: 'ban-hang', name: 'Mẫu website bán hàng', count: websiteTemplates.filter(w => w.categoryId === 'ban-hang').length },
    { id: 'dich-vu', name: 'Mẫu website dịch vụ', count: websiteTemplates.filter(w => w.categoryId === 'dich-vu').length },
    { id: 'landing-page', name: 'Mẫu website Landing page', count: websiteTemplates.filter(w => w.categoryId === 'landing-page').length },
    { id: 'thong-tin', name: 'Mẫu website thông tin', count: websiteTemplates.filter(w => w.categoryId === 'thong-tin').length },
]

export function getTranslatedTemplate(template: WebsiteTemplate, locale: string): WebsiteTemplate {
    if (locale !== 'en') return template;

    const titleTranslations: Record<string, string> = {
        'mau-website-ban-hang-cong-nghe-radios-home-2': 'Tech E-commerce Website - Radios Home 2',
        'mau-website-noi-that-hama': 'Interior Design Website - Hama',
        'mau-website-noi-that-sns-market': 'Furniture & Decor Website - Sns Market',
        'mau-website-ban-hang-noi-that-big-bazaar-home-4': 'Interior Sales Website - Big Bazaar Home 4',
        'mau-website-dich-vu-noi-that-cozy': 'Interior Service Website - Cozy',
        'mau-website-dich-vu-noi-that-ollis-5': 'Mattress & Interior Website - Ollis 5',
        'mau-website-ban-hang-ke-noi-that-ollis-4': 'Furniture Shelves Website - Ollis 3',
        'mau-website-thiet-ke-noi-that-home-decor-blocksy': 'Home Decor Website - Blocksy',
        'mau-website-noi-that-kuteshop': 'Furniture & Boutique - Kuteshop',
        'mau-website-ban-hang-noi-that-basel': 'Classic Furniture Website - Basel',
        'mau-website-ban-hang-phu-kien-trang-tri-seese-home-1': 'Decor Accessories Website - Seese Home 1',
        'mau-website-ban-hang-phu-kien-trang-tri-seese': 'Decor Accessories Website - Seese',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-vura': 'Interior Boutique Website - Vura',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-retbo': 'Bespoke Decor Website - Retbo',
        'mau-website-ban-hang-noi-that-gravity': 'Luxury Furniture Website - Gravity',
        'mau-website-ban-hang-noi-that-woodmart': 'Premium Furniture E-commerce - Woodmart',
        'mau-website-ban-hang-noi-that-kora': 'Modern Furniture Store - Kora',
        'mau-website-ban-hang-noi-that-karo': 'Bespoke Interior Store - Karo',
        'mau-website-ban-hang-noi-thoi-khoa-cu-smartlock': 'Smart Door Lock Store - Smartlock',
        'mau-website-ban-hang-noi-that-mueble': 'Minimalist Furniture Store - Mueble',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-arano': 'Premium Decor & Design - Arano',
        'mau-website-giao-duc-blockchain': 'Blockchain Education Platform',
        'mau-website-yoga-tri-lieu': 'Therapeutic Yoga & Wellness Center',
        'mau-website-smarthome': 'Smart Home & Tech Solutions',
        'mau-website-tham-my-vien': 'International Beauty & Spa Clinic',
        'mau-website-tieng-anh': 'English Learning Center',
        'mau-website-trang-suc': 'Luxury Jewelry E-commerce',
        'mau-website-du-thuyen-vinh-ha-long': 'Ha Long Bay Luxury Cruise Booking',
        'mau-website-ban-hang-my-pham-avesa-home-2': 'Luxury Cosmetics Store - Avesa Home 2',
        'mau-website-ban-hang-san-pham-nong-nghiep-vano': 'Organic Farm Produce - Vano',
        'mau-website-ban-nuoc-hoa-perfume-store-2': 'Premium Perfume Store - Perfume Store 2',
        'mau-website-dich-vu-ca-phe-barista-modern': 'Modern Cafe & Bistro - Barista Modern',
        'mau-website-dich-vu-du-lich-adventis': 'Travel & Tour Booking - Adventis',
        'mau-website-dich-vu-du-lich-sealosca': 'Ocean & Beach Resort Tour - Sealosca',
        'mau-website-dich-vu-dinh-cu-visa-travisa': 'Immigration & Visa Consultancy - Travisa',
        'mau-website-dich-vu-khach-san-the-resort': 'Luxury Resort & Hotel Booking',
        'mau-website-dich-vu-nha-hang-gofoodie': 'Fine Dining Restaurant - Gofoodie',
        'mau-website-dich-vu-nha-hang-grand-restaurant': 'Events & Wedding Venue - Grand Restaurant',
        'mau-website-dich-vu-nha-hang-organic-restaurant': 'Healthy Organic Eatery - Organic Restaurant',
        'mau-website-dich-vu-nha-hang-ristera': 'Buffet & BBQ Bistro - Ristera',
        'mau-website-dich-vu-nha-hang-sovy-2': 'Family Restaurant & Diner - Sovy 2',
        'mau-website-dich-vu-tiec-cuoi-bridely': 'Bespoke Wedding Planner - Bridely',
        'mau-website-dich-vu-tiec-cuoi-wedda': 'Wedding Planner & Organizer - Wedda',
        'mau-website-cong-ty-bat-dong-san': 'Real Estate Agency Website',
        'mau-website-ca-nhan-moi-gioi-bat-dong-san': 'Real Estate Agent Personal Website',
        'mau-website-tap-doan-bat-dong-san-2': 'Real Estate Corporation Website',
        'mau-website-du-an-nha-o-chuong-duong-homeland': 'Chương Dương Homeland Project Landing Page',
        'mau-website-mua-ban-nha-dat': 'Property Listing & Portal Website'
    };

    const descTranslations: Record<string, string> = {
        'mau-website-ban-hang-cong-nghe-radios-home-2': 'Professional e-commerce layout, modern design, fully responsive on all devices and optimized for SEO.',
        'mau-website-noi-that-hama': 'Hama interior website template with modern and eye-catching interface. Responsive and SEO friendly.',
        'mau-website-noi-that-sns-market': 'Professional Sns Market furniture template with a modern look, responsive layout, and clean SEO code.',
        'mau-website-ban-hang-noi-that-big-bazaar-home-4': 'Big Bazaar Home 4 furniture sales template with modern layout, high-conversion structure, and SEO standards.',
        'mau-website-dich-vu-noi-that-cozy': 'Cozy interior services template featuring warm, elegant aesthetic, fully responsive and SEO optimized.',
        'mau-website-dich-vu-noi-that-ollis-5': 'Ollis 5 minimalist mattress and home interior services website template. Optimizes user experience and speed.',
        'mau-website-ban-hang-ke-noi-that-ollis-4': 'Ollis 3 furniture shelves sales store layout, professional design, fully responsive across desktop and mobile.',
        'mau-website-thiet-ke-noi-that-home-decor-blocksy': 'Perfect starter layout for interior design studios, featuring minimalist and clean modern structure.',
        'mau-website-noi-that-kuteshop': 'Kute Shop is a lovely, cozy furniture template with an extremely engaging catalog design.',
        'mau-website-ban-hang-noi-that-basel': 'Basel design blends classic and contemporary styles, perfect for diverse high-end furniture items.',
        'mau-website-ban-hang-phu-kien-trang-tri-seese-home-1': 'Focuses on displaying decor items and home accessories with a clean, grid-based masonry layout.',
        'mau-website-ban-hang-phu-kien-trang-tri-seese': 'Extended version of Seese series with smart grid layout, suitable for creative studio collections.',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-vura': 'Vura boutique store template, ideal for displaying items with strong visual personality.',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-retbo': 'Retbo is one of the most beautiful home accessories templates with soft pastel tones.',
        'mau-website-ban-hang-noi-that-gravity': 'Gravity template offers a powerful, elegant impression for premium luxury furniture boutiques.',
        'mau-website-ban-hang-noi-that-woodmart': 'Premium WooCommerce template built with Woodmart, highly optimized for large catalogs and high conversion.',
        'mau-website-ban-hang-noi-that-kora': 'Modern Kora layout with clean grid, responsive filter controls, and highly customizable homepage sections.',
        'mau-website-ban-hang-noi-that-karo': 'High-end Karo template, customized for elite design firms and premium retail stores.',
        'mau-website-ban-hang-noi-thoi-khoa-cu-smartlock': 'Smartlock store layout, highlighting smart lock hardware with high-converting spec listings.',
        'mau-website-ban-hang-noi-that-mueble': 'Minimalist Mueble furniture design with high whitespace, clean typography, and fast page loads.',
        'mau-website-ban-hang-phu-kien-trang-tri-noi-that-arano': 'Arano template brings a sleek premium design for home styling consultancies and boutique accessory stores.',
        'mau-website-giao-duc-blockchain': 'Specialized blockchain education platform for universities and academies to post courses, tech updates, and certifications.',
        'mau-website-yoga-tri-lieu': 'A serene matcha-green yoga and meditation center template, creating a relaxing feel for visitors.',
        'mau-website-smarthome': 'Smart home technology layout, introducing smart automation devices and installation services for villas.',
        'mau-website-tham-my-vien': 'A premium luxury layout for spas, aesthetic clinics, and dermatology centers with Gold/Gold accents.',
        'mau-website-tieng-anh': 'Dynamic English center template for kids and adults, with trial registration and level tests.',
        'mau-website-trang-suc': 'Luxury jewelry template designed for high-resolution diamond and gemstone closeups.',
        'mau-website-du-thuyen-vinh-ha-long': 'High-end booking landing page for Ha Long Bay cruises, highlighting panoramic ship views.',
        'mau-website-ban-hang-my-pham-avesa-home-2': 'Luxury makeup and skincare shop template with delicate, modern design, fully responsive.',
        'mau-website-ban-hang-san-pham-nong-nghiep-vano': 'Organic grocery and green farm produce shop template, showcasing fresh fruits and vegetables.',
        'mau-website-ban-nuoc-hoa-perfume-store-2': 'Exquisite perfume and cosmetics shop template featuring a mysterious, luxury design.',
        'mau-website-dich-vu-ca-phe-barista-modern': 'Bespoke cafe and milk tea shop layout displaying menus, ambient photos, and online ordering.',
        'mau-website-dich-vu-du-lich-adventis': 'Modern travel agency website with tour packages, detailed itineraries, and online bookings.',
        'mau-website-dich-vu-du-lich-sealosca': 'Stunning beach tour and coastal resort booking template, featuring ocean-themed visuals.',
        'mau-website-dich-vu-dinh-cu-visa-travisa': 'Professional consultancy layout for immigration agents, visa services, and study abroad packages.',
        'mau-website-dich-vu-khach-san-the-resort': 'Luxury hotel and boutique resort template with integrated booking calendars.',
        'mau-website-dich-vu-nha-hang-gofoodie': 'Beautiful restaurant website showcasing gourmet menus and quick table reservations.',
        'mau-website-dich-vu-nha-hang-grand-restaurant': 'Grand restaurant and wedding venue template with classical, premium aesthetic.',
        'mau-website-dich-vu-nha-hang-organic-restaurant': 'Healthy dining and organic vegan restaurant template, showcasing eco-friendly ingredients.',
        'mau-website-dich-vu-nha-hang-ristera': 'Buffet, BBQ, and hotpot restaurant website featuring modern grid layout and promotions.',
        'mau-website-dich-vu-nha-hang-sovy-2': 'Warm family diner and restaurant website with a clean interface for quick delivery bookings.',
        'mau-website-dich-vu-tiec-cuoi-bridely': 'Bridely wedding planning agency template featuring romantic aesthetics and wedding packages.',
        'mau-website-dich-vu-tiec-cuoi-wedda': 'Modern wedding planner and photo album template, celebrating couples and events.',
        'mau-website-cong-ty-bat-dong-san': 'Professional real estate agency website template, featuring modern project grids and visual contact links.',
        'mau-website-ca-nhan-moi-gioi-bat-dong-san': 'Personal website template for real estate agents, optimizing personal branding and messaging channels.',
        'mau-website-tap-doan-bat-dong-san-2': 'High-end real estate group portal template, managing project portfolios and corporate information.',
        'mau-website-du-an-nha-o-chuong-duong-homeland': 'Modern apartment showcase and landing page template with maps and registration forms.',
        'mau-website-mua-ban-nha-dat': 'Property buying, listing, and portal website template with advanced property filter controls.'
    };

    const categoryLabelTranslations: Record<string, string> = {
        'Mẫu website bán hàng': 'E-commerce Website',
        'Mẫu website dịch vụ': 'Service Website',
        'Mẫu website giáo dục': 'Education Website',
        'Mẫu website nội thất': 'Interior Website',
        'Mẫu website bất động sản': 'Real Estate Website',
        'Mẫu website giới thiệu': 'Corporate Website'
    };

    const tagTranslations: Record<string, string> = {
        'Mỹ phẩm': 'Cosmetics',
        'Bán hàng': 'Selling',
        'Trang sức': 'Jewelry',
        'Vàng bạc': 'Gold/Silver',
        'Luxury': 'Luxury',
        'Nông sản': 'Agriculture',
        'Rau củ': 'Vegetables',
        'Nước hoa': 'Perfume',
        'Cafe': 'Coffee',
        'Trà sữa': 'Milk Tea',
        'Đặt món': 'Ordering',
        'Du lịch': 'Travel',
        'Đặt tour': 'Tour Booking',
        'Biển đảo': 'Island/Beach',
        'Resort': 'Resort',
        'Định cư': 'Immigration',
        'Visa': 'Visa',
        'Du học': 'Study Abroad',
        'Khách sạn': 'Hotel',
        'Homestay': 'Homestay',
        'Nhà hàng': 'Restaurant',
        'Đặt bàn': 'Table Booking',
        'Ẩm thực': 'Cuisine',
        'Tiệc cưới': 'Wedding',
        'Sự kiện': 'Event',
        'Đồ chay': 'Vegan',
        'Buffet': 'Buffet',
        'Lẩu nướng': 'BBQ/Hotpot',
        'Quán ăn': 'Diner',
        'Trung tâm': 'Center',
        'Album cưới': 'Wedding Album',
        'Yoga': 'Yoga',
        'Sức khỏe': 'Health',
        'Thiền định': 'Meditation',
        'Smarthome': 'Smarthome',
        'Nhà thông minh': 'Smart Home',
        'Công nghệ': 'Technology',
        'Bất động sản': 'Real Estate',
        'Dự án': 'Project',
        'Căn hộ': 'Apartment',
        'Chung cư': 'Condo',
        'Đào tạo': 'Training',
        'E-learning': 'E-learning',
        'Học thử': 'Trial Class',
        'Du thuyền': 'Cruise',
        'Hạ Long': 'Ha Long',
        'Tour du lịch': 'Tour',
        'Thiết kế': 'Design',
        'Nội thất': 'Interior',
        'Mẫu Blocksy': 'Blocksy Theme',
        'Tiếng Anh': 'English',
        'Bóng thể thao': 'Sportswear',
        'Thiết bị': 'Equipment',
        'Thang máy': 'Elevator',
        'Cửa thông minh': 'Smart Door',
        'Thơ mộng': 'Poetic',
        'Khóa cửa': 'Smart Lock',
        'Học tập': 'Learning',
        'Responsive': 'Responsive',
        'SEO': 'SEO',
        'Thiết kế đẹp': 'Beautiful Design',
        'Tối giản': 'Minimalist',
        'Modern': 'Modern',
        'E-commerce': 'E-commerce',
        'Trang trí': 'Decor',
        'Phụ kiện': 'Accessories',
        'Decor': 'Decor',
        'Boutique': 'Boutique'
    };

    const featureTranslations: Record<string, string> = {
        'Tặng tên miền quốc tế .com': 'Free international .com domain',
        'Tặng Hosting 4 GB': 'Free 4 GB High-speed Hosting',
        'Thiết kế chuẩn UX/UI': 'Standard UX/UI Design',
        'Tối ưu chuẩn SEO': 'SEO Friendly Optimization',
        'Bảo hành trọn đời': 'Lifetime Warranty',
        'Hỗ trợ kỹ thuật trọn đời': 'Lifetime Technical Support'
    };

    const detailLabelTranslations: Record<string, string> = {
        'Thiết kế': 'Design',
        'Tính năng': 'Features',
        'SEO': 'SEO',
        'Bảo hành': 'Warranty'
    };

    const detailValueTranslations: Record<string, string> = {
        'Responsive, Mobile First': 'Responsive, Mobile First',
        'Đầy đủ tính năng, Quản trị dễ dàng': 'Fully featured, Easy management',
        'Tối ưu SEO On-page': 'Optimized On-page SEO',
        'Trọn đời': 'Lifetime',
        'WooCommerce tích hợp': 'WooCommerce Integrated',
        'Tối ưu tốc độ tải trang': 'Page Load Optimized',
        'Basel Framework': 'Basel Framework',
        'Mega Menu': 'Mega Menu',
        'Tối ưu hình ảnh': 'Image Optimized',
        'Sáng, Hiện đại': 'Bright, Modern',
        'Tích hợp lọc sản phẩm': 'Product Filter Integrated',
        'Tối ưu On-page': 'On-page Optimized',
        'Cấu trúc web chuẩn': 'Standard Web Structure',
        'Boutique Store': 'Boutique Store',
        'Thanh toán dễ dàng': 'Easy Checkout',
        'Tốc độ cực nhanh': 'Ultra-fast Speed',
        'Giao diện pastel': 'Pastel Interface',
        'Phân loại danh mục tốt': 'Good Categorization',
        'Giao diện thân thiện SEO': 'SEO Friendly Interface',
        'Sang trọng, Đẳng cấp': 'Luxury, High-class',
        'Chuyên nghiệp': 'Professional',
        'Tối ưu trải nghiệm': 'UX Optimized',
        'Đơn giản, hiện đại': 'Simple, Modern',
        'Tone màu xanh matcha dịu mát': 'Refreshing Matcha Green',
        'Đăng ký thẻ tập, xem lịch lớp': 'Register gym card, view schedule',
        'Tối ưu hóa hình ảnh': 'Image Optimized',
        'Hiện đại, đậm chất tech': 'Modern Tech-rich Design',
        'Báo giá nhanh thiết bị': 'Quick Quote Feature',
        'On-page chuẩn': 'Standard On-page SEO',
        'Luxury, tone vàng gold': 'Gold Luxury Accent',
        'Đặt lịch hẹn trực tuyến': 'Book Appointments Online',
        'Chuẩn UX/UI y khoa': 'Medical UI/UX Standards',
        'Tươi sáng, năng động': 'Bright, Dynamic',
        'Đăng ký học thử, test đầu vào': 'Trial Registration & Placement Test',
        'Load cực nhanh': 'Ultra-fast Loading',
        'Tối giản, quý phái': 'Minimalist, Noble',
        'Zoom sản phẩm độ nét cao': 'High-definition Product Zoom',
        'Thân thiện di động': 'Mobile Friendly',
        'Sang trọng, phóng khoáng': 'Luxury, Spacious',
        'Đặt tour, kiểm tra phòng trống': 'Book Tour, Check Room Availability',
        'Tập trung từ khóa du lịch': 'Target Travel Keywords',
        'Công nghệ, hiện đại': 'Modern Technology',
        'Video học tập, cấp chứng chỉ': 'Learning Videos & Certificates',
        'Cấu trúc bài viết chuẩn': 'Standard Post Structure',
        'Sang trọng, tinh tế': 'Elegant, Sophisticated',
        'Mua hàng nhanh, thanh toán': 'Quick buy & easy checkout',
        'Chuẩn SEO Onpage': 'Onpage SEO Standards',
        'Tươi sáng, thiên nhiên': 'Bright, Nature-inspired',
        'Đặt hàng, cân nặng sản phẩm': 'Order Placement & Weights',
        'Chuẩn SEO Google': 'Google SEO Standards',
        'Luxury, huyền bí': 'Mysterious Luxury',
        'Bộ lọc mùi hương, thương hiệu': 'Fragrance & Brand Filters',
        'Onpage hoàn hảo': 'Perfect Onpage SEO',
        'Tone màu ấm cúng, vintage': 'Cozy Vintage Tones',
        'Hiển thị menu, đặt ship': 'Display Menu & Ordering',
        'Năng động, tươi trẻ': 'Dynamic & Young',
        'Đặt tour, lịch trình chi tiết': 'Book tour & Detailed itinerary',
        'Cấu trúc tour chuẩn SEO': 'SEO-structured Tours',
        'Xanh dương đại dương': 'Ocean Blue Theme',
        'Đặt phòng, hiển thị tour': 'Room Booking & Tour Display',
        'Load nhanh, chuẩn Google': 'Fast Load, Google Standard',
        'Tin cậy, chuyên nghiệp': 'Trustworthy & Professional',
        'Đăng ký tư vấn, dịch vụ trọn gói': 'Request Consultation & Full Pack',
        'Đầy đủ schema metadata': 'Full Metadata Schema',
        'Luxury, tối giản': 'Luxury, Minimalist',
        'Booking phòng trực tiếp': 'Direct Room Booking',
        'Tối ưu tốc độ load': 'Load Speed Optimized',
        'Hiện đại, trực quan': 'Modern, Intuitive',
        'Đặt bàn trước, hiển thị menu': 'Pre-book Table & Display Menu',
        'Cổ điển, sang trọng': 'Classic, Elegant',
        'Đặt phòng tiệc, liên hệ nhanh': 'Book Party Room & Quick Contact',
        'Mộc mạc, thiên nhiên': 'Rustic, Organic',
        'Xem thực đơn, đặt món online': 'View Menu & Order Online',
        'Google Index nhanh': 'Fast Google Indexing',
        'Trẻ trung, hiện đại': 'Youthful, Modern',
        'Hiển thị các combo, khuyến mãi': 'Show Combos & Discounts',
        'Tốc độ load cực cao': 'High Load Speed',
        'Đơn giản, tinh tế': 'Simple, Refined',
        'Đặt giao hàng tận nơi': 'Place Delivery Orders',
        'Tương thích di động': 'Mobile Compatibility',
        'Thanh lịch, lãng mạn': 'Elegant, Romantic',
        'Chọn sảnh tiệc, menu tiệc cưới': 'Select Ballroom & Wedding Menu',
        'Load nhanh, chuẩn': 'Fast Load, Standard',
        'Thơ mộng, tươi sáng': 'Dreamy, Bright',
        'Xem album ảnh cưới, bản đồ': 'View Wedding Album & Map',
        'Tìm kiếm nâng cao, bản đồ': 'Advanced Search & Map API',
        'Tối giản, hiện đại': 'Minimalist, Modern',
        'Xem căn hộ mẫu 3D, liên hệ': '3D Apartment Tour & Contact'
    };

    return {
        ...template,
        title: titleTranslations[template.slug] || template.title,
        description: descTranslations[template.slug] || template.description,
        price: template.price === 'Liên hệ' ? 'Contact' : template.price,
        time: template.time ? template.time.replace('ngày', 'days') : template.time,
        categoryLabel: categoryLabelTranslations[template.categoryLabel] || template.categoryLabel,
        tags: template.tags ? template.tags.map(tag => tagTranslations[tag] || tag) : template.tags,
        features: template.features ? template.features.map(f => featureTranslations[f] || f) : template.features,
        details: template.details ? template.details.map(d => ({
            label: detailLabelTranslations[d.label] || d.label,
            value: detailValueTranslations[d.value] || d.value
        })) : template.details
    };
}

export function getTranslatedTemplates(templates: WebsiteTemplate[], locale: string): WebsiteTemplate[] {
    return templates.map(t => getTranslatedTemplate(t, locale));
}

